# Generated by Django 4.2.3 on 2023-09-11 15:13

from django.db import migrations, models
import django.db.models.deletion
import news.models.news_model


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        error_messages={
                            "title": ["Este campo não pode estar vazio."]
                        },
                        max_length=200,
                        validators=[news.models.news_model.is_one_word],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        error_messages={
                            "content": ["Este campo não pode estar vazio."]
                        }
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        error_messages={
                            "created_at": ["Este campo não pode estar vazio."]
                        }
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        error_messages={
                            "author": ["Este campo não pode estar vazio."]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.users",
                    ),
                ),
                ("categories", models.ManyToManyField(to="news.categories")),
            ],
        ),
    ]
